version: "3"
services:
  app:
    build: . 
    image: 3doae
    #image: nvcr.io/nvidia/pytorch:21.06-py3
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: 3doae
    user: ${CURRENT_UID}
    volumes:
      - /home/hyoshida:/home/hyoshida
      - /etc/passwd:/etc/passwd      
      - /etc/group:/etc/group
     #ports:
     # - "6007:6007"
     # - "8899:8899"
    tty: true
    working_dir: $HOME
    #command: tail -f /dev/null
    stdin_open: true
